### ISSUE TITLE
Add community guidelines to the documentation or README

### ISSUE THREAD

**Issue by sadielbartholomew** [Climdyn/qgs#1]
Towards my review in openjournals/joss-reviews#2597 I have identified that there is not a clear and accessible description for, quoting the review checklist, " third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support".

Please provide this information in a readily-available location, in practice the documentation and/or README file. A few paragraphs could suffice to cover those three components. Thanks.

**Comment by jodemaey** [comment]
Hi, 

Thank you for raising that issue.
This issue was also raised by @eviatarbach in his review and is adressed by the commits:

https://github.com/Climdyn/qgs/commit/f87022c6c1f5d5909129fdbba029566f07b1d2bb
https://github.com/Climdyn/qgs/commit/c6a7deefa29f730542a18a206026f269b4c16c2b

in the [joss](https://github.com/Climdyn/qgs/tree/joss) branch. These will be merged into the master when the review process is completed.

**Comment by sadielbartholomew** [comment]
Thanks @jodemaey, that addresses the issue well so I will close this. I have now ticked the relevant review checklist item.
