### ISSUE TITLE
Field plots

### ISSUE THREAD

**Issue by patnr** [Climdyn/qgs#9]
Hi!

I want to do some DA experiments with MAOOAM in DAPPER. It seems qgs is the main package being developed, and the JOSS paper says it's quicker than the initial Python-MAOOAM implementation, so I was thinking to use qgs.

I always want to be able to visualize the physical system I'm working on. Not just in phase space, but the actual fields.

Do you have some code for accomplishing this? I tried looking into jodemaey/movie-script and the repos of S. G. Penny, but nothing stands out as immediately viable.

**Comment by jodemaey** [comment]
Hi Patrick,

It is indeed still missing in qgs but planned for the next v0.3.0 release (see [here](https://github.com/Climdyn/qgs/projects/2), it is the Visualization toolbox item).

I have almost finished the previous item (writing an user guide), so this is my very next step! 

Meanwhile it is still possible to use the jodemaey/movie-script code but indeed it is quite outdated and not very convenient.

I will keep you informed about the development of the visualization and push directly when I have a nearly viable stub.

Thanks for you interest in qgs,

Jonathan.

**Comment by patricknraanes** [comment]
Ok, cool! I'll keep an eye out!

**Comment by jodemaey** [comment]
Hi Patrick,

I'm coming back to you because the visualization of the model is now easier with the new release v0.2.4.
This has been done through the implementation of "diagnostic" objects which post-process the output of the model to create the fields and derived variables, and their methods allow to plot the result or create animation and movies.
You can check on how to use them in the [User Guide](https://qgs.readthedocs.io/en/latest/files/user_guide.html#using-qgs-once-configured).

There are also examples in the documentation: [here](https://qgs.readthedocs.io/en/latest/files/examples/RP.html) and [here](https://qgs.readthedocs.io/en/latest/files/examples/DDV.html).

Finally, the notebooks folder also contain examples. 

It is also possible to create your own model diagnostics using the diagnostic base classes.

If you have any question or need support, feel free to ask !

Cheers,

Jonathan.

**Comment by patricknraanes** [comment]
Thanks for the return! It looks great!

Unfortunately I was not able to test it right now, due to #10 . But I will soon have access to a Linux system, so I can try!

**Comment by jodemaey** [comment]
With the introduction of the diagnostic classes, this issue is considered as solved.
